version: '2'

services:

  redzilla:
    image: opny/redzilla:latest
    networks:
      - redzilla
      - raptor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ./config:/app/config
    ports:
      - 3000:3000
    environment:
      REDZILLA_IMAGENAME: raptorbox/node-red
      REDZILLA_NETWORK: raptorworkflowmanager_redzilla
      REDZILLA_DOMAIN: workflow.localhost
      REDZILLA_ENV: NODERED
      NODERED_CONFIG: /data/config/workflow.json

networks:
  redzilla:
    driver: bridge
  raptor:
    external:
      name: raptor_raptor_net
