version: '2'

services:

  redzilla:
    image: opny/redzilla:latest
    networks:
      - redzilla
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 3000:3000
    environment:
    #   REDZILLA_IMAGE: raptorbox/node-red
      REDZILLA_NETWORK: raptorworkflowmanager_redzilla
      REDZILLA_DOMAIN: workflow.localhost

networks:
  redzilla:
    driver: bridge
