version: '2'

services:

  redzilla:
    image: opny/redzilla:latest
    networks:
      - redzilla
      - raptor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 3000:3000
    environment:
      REDZILLA_LOGLEVEL: debug
      REDZILLA_IMAGE: raptorbox/node-red
      REDZILLA_NETWORK: raptorworkflowmanager_redzilla
      REDZILLA_DOMAIN: workflow.localhost
      REDZILLA_ENVPREFIX: nodered
      NODERED_CONFIG: /data/config/workflow.json

    extra_hosts:
      - "raptor.local:172.16.238.1"


networks:
  redzilla:
    driver: bridge
  raptor:
    external:
      name: raptor_raptor_test
